name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sound library
      run: sudo apt-get install libasound2-dev
    - name: Lint sound
      run: cd sound; cargo clippy -- -D warnings
    - name: Build sound
      run: cd sound; cargo build --verbose
    - name: Run tests on sound
      run: cd sound; cargo test --verbose
